### ISSUE TITLE
Framework

### ISSUE THREAD

**Issue by harukaza** [lytum/joint-intent-classification-and-slot-filling-based-on-BERT#1]
Hello，What framework does your code run in？ Thanks you.

**Comment by lytum** [comment]
> 
> 
> Hello，What framework does your code run in？ Thanks you.

The pre-trained BERT model is used, more detailed information please read the following link:
https://tfhub.dev/google/bert_uncased_L-12_H-768_A-12/1

**Comment by harukaza** [comment]
Thank you very much
